### get request
GET http://localhost:4004/trainingsrv/trainers

### create
POST http://localhost:4004/trainingsrv/trainers
Content-Type: application/json

{
      "name": "BTP-Bootcamp",
      "skill": "CAPM",
      "trainer": "XYZ",
      "location": "Virtual",
      "room": "Zoom",
      "trainee": null,
      "duration": "9"   
}

### get request
GET http://localhost:4004/trainingsrv/trainers/210c8132-6a70-4d92-9291-ab210cfa2478

### patch

PUT http://localhost:4004/trainingsrv/trainers/210c8132-6a70-4d92-9291-ab210cfa2478
Content-Type: application/json

{
      "name": "BTP-training"  
}

### delete request
DELETE http://localhost:4004/trainingsrv/trainers/210c8132-6a70-4d92-9291-ab210cfa2478
Content-Type: application/json

{ }